name: TVHeadEnd
version: "0.09994"
slug: tvheadend
description: TVHeadEnd server
url: "https://github.com/neopilou/hassio-addons"
webui: "http://[HOST]:[PORT:9981]"
init: false
map:
  - addons:rw 
ports: 
  9981/tcp: 9981
  9982/tcp: 9982
  554/udp: 554
ports_description:
  9981/tcp: For HTTP (web) server
  9982/tcp: For HTSP server
  554/udp: For UDP
arch: 
  - aarch64
  - amd64
  - armhf
