name: TVHeadEnd
version: "0.0999992"
slug: tvheadend
description: TVHeadEnd server
url: "https://github.com/neopilou/hassio-addons" 
full_access: true
init: false
map:
  - addons:rw 
ports: 
  9981/tcp: 9981
  9982/tcp: 9982
ports_description:
  9981/tcp: Web Interface (Not required for Ingress)
  9982/tcp: HTSP server
host_network: true
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
arch: 
  - aarch64
  - amd64
  - armhf
